### ISSUE TITLE
text boxe don't disapear

### ISSUE THREAD

**Issue by chevalier-nomo** [rflafla/kwin-walk-through-desktop#1]
After I walk from one desktop to another, the text boxes (on desktop 1, desktop 2) don't disappear. They need to be clicked on to make them disappear. Another way to resolve this would be to disable the box (is there a way to do this?).

I am using:

    KDE 6
    Manjaro
    X11

**Comment by rflafla** [comment]
On my computer, I observe this behavior if I release the meta and tab keys simultaneously, but if I release them with a slight time interval, the OSD disappears.
Does the bug only occur when you release both keys at the same time?
To hide the OSD, you can also press any key.

I'll work on the fix as soon as possible

**Comment by chevalier-nomo** [comment]
No, I tried to release the Meta and Tab keys at different times, but the text box didn't disappear. I also tried pressing different keys, but the only thing that seems to make it disappear is clicking on the box with my mouse.

**Comment by rflafla** [comment]
After investigating, the problem occurred with X11 and not with Wayland.
Unfortunately, I couldn't find a fix for X11.
Instead, I've added an auto-hide function after a configurable delay (500ms by default).
I hope this helps.
I'll let you know if I find another way

**Comment by chevalier-nomo** [comment]
thanks, it work great for me now!

**Comment by evamiaou** [comment]
Hi. This problem seems to have gotten worse. It used to be the box would disappear after pressing meta again but now it stays forever until i go into overview mode and close the window.
I could not find the configurable delay, and it doesn't work anyway.

OS: Fedora Linux 41 (KDE Plasma) x86_64
Host: ROG Strix G814JV_G814JV (1.0)
Kernel: Linux 6.11.11-300.fc41.x86_64
DE: KDE Plasma 6.2.4
WM: KWin (Wayland)
WM Theme: Klassy

Installed the plugin from the store inside the kwin script settings.

If this is still being maintained and you want to change the settings, please add something that just disables the box entirely. I don't need it and it seems like OP considered that too. If you don't want to maintain this anymore i can take a crack at it.

**Comment by rflafla** [comment]
Hi,
Even if the box is not displayed, the script must have focus to run properly.
With a small fix and the new KDE version, the behavior is better with Wayland, and that is what I personally expect.

I had to test with X11 before updating the script.
Unfortunately, it's still buggy with X11, but it's no worse with the fix.

The script is updated in the KDE store and can be downloaded.

**Comment by evamiaou** [comment]
Thanks for the fix!
